---
title: "Code Testing"
author: "Chandler Ellsworth"
date: "2023-11-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)

```

```{r}
nba_data <- read_csv("nba_2022-23_all_stats_with_salary.csv")
head(nba_data)

nba_data <- nba_data %>%
  mutate(Team = if_else(grepl("/", Team), substr(Team, 5, 7), substr(Team, 1, 3)),
         Position = if_else(grepl("-", Position), substr(Position, 4, 5), substr(Position, 1, 2))) %>%
  rename(Minutes_Per_Game = MP, 
         Field_Goals_Made_Per_Game = FG,
         Field_Goal_Percentage = 'FG%',
         Three_Pointers_Made_Per_Game = '3P',
         Two_Pointers_Made_Per_Game = '2P',
         Assists_Per_Game = AST,
         Points_Per_Game = PTS,
         Player_Efficiency_Rating = PER,
         True_Shooting_Percentage = 'TS%',
         Win_Shares = WS)

names(nba_data %>%
        select(contains("_")))

```

```{r plot-wider, fig.width=10, fig.height=4}
library(ggrepel)
position <- "SG"
stats <- "AST"
position_filter <- nba_data %>%
  filter(Position == position)

ggplot(position_filter, aes(x = !!(as.name(stats)), y = Salary/1000000, color = Age)) +
  geom_point() +
  labs(x = paste0(stats, " Per Game"),
       y = "Salary ($M)",
       title = paste0("Salary Based on ", stats, " per game for the ", position, " position")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  geom_text_repel(aes(label = position_filter$`Player Name`), 
            size = 2.2,
            hjust = 0.5,
            vjust = -1) +
  scale_color_gradient(low = "blue", high = "red")


```


```{r}
ggplot(nba_data, aes(x = PTS, y = Salary)) +
        geom_point()
```


```{r plot-wider, fig.width=10, fig.height=4}
team <- "GSW"
variable <- "Minutes_Per_Game"

team_filter <- nba_data %>%
  filter(Team == team)

ggplot(team_filter, aes(x = reorder(`Player Name`, -Salary), y = Salary)) +
  geom_bar(stat="identity", fill = "orange") +
  labs(x = "Player Name",
       y = variable,
       title = paste0(variable, " By Player On The ", team, " Team For The 2022-23 Season")) +
  theme(plot.title = element_text(hjust = 0.5)) +
  scale_x_discrete(guide = guide_axis(n.dodge=2)) +
  geom_text(aes(label = Salary), size = 3, position=position_dodge(width=0.9), vjust=-0.25) +
  facet_wrap(~Position, scales ="free_y", ncol = 1, strip.position = "left")


newData <- nba_data %>% 
      filter(Position == "SG") %>%
      select(Minutes_Per_Game)
mean(newData[[1]])
paste("The Average", "input$stat", "for the", "input$position", "Position is", 
            round(mean(newData[[1]], na.rm = TRUE), 2))
```

```{r}
if (2+2 == 4) {
  writeLines(c(paste("test"), paste("tw")))
}
help("writeLines")

nba_data %>% 
        filter(Position == "PG") %>%
        select(`Player Name`, Salary) %>%
        top_n(10)

```

```{r}

newData3 <- nba_data %>%
      filter(Salary >= 20000 & Salary <= 20000000) %>%
      select(Position, Minutes_Per_Game)

paste("The mean for the PG Position is", 
                      format(round(mean(select(filter(newData3, Position == "PG"), Minutes_Per_Game)[[1]], na.rm = TRUE) 2),  big.mark = ",", scientific = FALSE), ", ",
                      format(round(mean(select(filter(newData3, Position == "SG"), Minutes_Per_Game)[[1]], na.rm = TRUE) 2),  big.mark = ",", scientific = FALSE), " for the SG Position")

format(round(mean(select(filter(newData3, Position == "PG"), Minutes_Per_Game[[1]]), na.rm = TRUE) 2),  big.mark = ",", scientific = FALSE)

round(mean(select(filter(newData3, Position == "PG"), Minutes_Per_Game)[[1]]), 2)
```

```{r}
    index <- createDataPartition(nba_data$Salary, 
                                 p = .8, 
                                 list = FALSE)
    #create training and test set by indexing index object
    train_set <- nba_data[index, ]
    test_set <- nba_data[-index, ]
    train_set
```

Points_Per_Game, Minutes_Per_Game, Assists_Per_Game, Win_Shares, Field_Goals_Made_Per_Game
```{r}
    index <- createDataPartition(nba_data$Salary, 
                                 p = 0.8, 
                                 list = FALSE)
    #create training and test set by indexing index object
    train_set <- nba_data[index, ]
    test_set <- nba_data[-index, ]
    
    rf_train_set <- train_set %>%
      select(Salary, Team, Position, Age, Points_Per_Game, Player_Efficiency_Rating, True_Shooting_Percentage, Win_Shares) %>%
      drop_na()
    
    na.omit(rf_train_set)
    
    which(is.na(rf_train_set))
    
    which(is.na(rf_test_set))
    
    rf_test_set <- test_set %>%
      select(Salary, Team, Position, Age, Points_Per_Game, Player_Efficiency_Rating, True_Shooting_Percentage, Win_Shares)
    
    rf_train_set %>% drop_na()
    
    test <- "Cross-Validation"
    
    if(test == "Cross-Validation") {
      #set up the train control parameters we want
      tr <- trainControl(method = 'cv',
                         number = 5)
    
    } else {
      #set up the train control parameters we want
      tr <- trainControl(method = 'repeatedcv',
                         number = 5,
                         repeats = 2)
    }
    
    grid <- expand.grid(mtry = seq(from = 1, to = 4, by = 1))
    
    (rf.fit <- train(Salary ~ .,
                    data = rf_train_set,
                    method = 'lm',
                    na.action = na.pass,
                    trControl = tr
                    ))
```


```{r}
library(randomForest)
    plot(varImp(rf.fit))
    plot(rf.fit)
    
    
    index <- createDataPartition(nba_data$Salary, 
                                 p = input$split, 
                                 list = FALSE)

    test_set <- nba_data[-index, ]
    
    mlr_test_set <- test_set %>%
      select(Salary, !!!input$mlrVars)
    
    preds <- predict(rf.fit, 
                     newdata = rf_test_set)
    
    test <-postResample(preds, rf_test_set$Salary)
    
    paste("test", test)
```


```{r}
[[1]]
Position

[[2]]
Age

[[3]]
Team

[[4]]
Points_Per_Game

[[5]]
Player_Efficiency_Rating

[[6]]
True_Shooting_Percentage

[[7]]
Win_Shares
```

```{r}
listy <- list("Position", "Age", "Team")
listy
```


```{r}
library(tidyverse)
filtered <- nba_data %>%
      select(Team, Position, Age, Points_Per_Game, Player_Efficiency_Rating, True_Shooting_Percentage, Win_Shares) %>%
      drop_na()

lapply(colnames(filtered), FUN = function(x) {
  
  if(class(filtered[[x]]) %in% c("factor", "character")) {
    print("test1")
  } else if (class(filtered[[x]]) %in% c("integer", "numeric")) {
    
    print("test2")
    
  }
})
test <- 2

names_ <- colnames(filtered)
names_    
inputs_ <- paste("mlr", names_, sep = "_")
inputs_
test2 <- lapply(inputs_, FUN = function(x){
  
  colname_ <- sub('.*_', '', x)
  #print(colname_)
  
  df <- data.frame(colname_,
                   value = get('test'))
    
})
test2
test3 <- bind_rows(test2)
pivot_wider(test3, names_from = colname_, values_from = value)
```


```{r}
filtered <- nba_data %>%
      select(Team, Age) %>%
      drop_na()
    
    names_ <- colnames(filtered)
    
    inputs_ <- paste("mlr", names_, sep = "_")
    listy <- list()
    listy <- list(pivot_wider(data.frame(colname_ = "Team",
                             value = "GSW"), names_from = colname_, values_from = value),
              pivot_wider(data.frame(colname_ = "Age",
                             value = 34), names_from = colname_, values_from = value))
    listy
    listy <- lapply(inputs_, FUN = function(x){
      
      colname_ <- sub('.*_', '', x)
      
      df <- data.frame(colname_,
                       value = get(paste0("input$",x)))
    }
    )
    listy
    df_ <- bind_cols(listy)
    df_
    newData_ <- pivot_wider(df_, names_from = colname_, values_from = value)
    
    predict(mlr(), 
            newdata = newData_)
    
    test <- data.frame(colname_ = "Team",
                             value = "GSW")
    pivot_wider(data.frame(colname_ = "Team",
                             value = "GSW"), names_from = colname_, values_from = value)
```


